export interface TextCustom {
    id: string,
    code: "LANDING_HERO_TITLE" | "LANDING_HERO_SUBTITLE" | 'LANDING_BLOC_1_TITLE' | 'LANDING_BLOC_1_CONTENT' | 'LANDING_BLOC_2_TITLE' | 'LANDING_BLOC_2_CONTENT' | 'LANDING_BLOC_3_TITLE' | 'LANDING_BLOC_3_CONTENT' | 'PARTNER_LIST_TITLE' | 'PARTNER_LIST_SUBTITLE' | 'CONTACT_TITLE' | 'CONTACT_FORM_TITLE',
    text: string
}